---

services:
  proxy:
    image: ghcr.io/applicreation/harmony-proxy:v0
    ports:
      - 80:80
  core:
    image: node:lts-alpine
    restart: on-failure
    ports:
      - 3000:3000
    command:
      - npm
      - run
      - dev
    working_dir: /app
    volumes:
      - ./.harmony/core:/root/.harmony:ro
      - ./app:/app
