---

services:
  proxy:
    image: ghcr.io/applicreation/harmony-proxy:v0
    ports:
      - 80:80
  core:
    image: node:lts-alpine
    restart: on-failure
    ports:
      - 3000:3000
    command:
      - npm
      - run
      - dev
    working_dir: /app
    env_file:
      - ./.harmony/core/.env
    volumes:
      - ./.harmony/core:/root/.harmony:ro
      - ./app:/app
  catalog:
    image: ghcr.io/applicreation/harmony-module-catalog:v0
    env_file:
      - ./.harmony/catalog/.env
    volumes:
      - ./.harmony/catalog:/root/.harmony:ro
  docs:
    image: ghcr.io/applicreation/harmony-module-docs:v0
    env_file:
      - ./.harmony/docs/.env
    volumes:
      - ./.harmony/docs:/root/.harmony:ro
