---

auth:
  clients:
    google:
      client_id: ${{GOOGLE_CLIENT_ID}}
      sensitive:
        client_secret: ${{GOOGLE_CLIENT_SECRET}}
        redirect_url: ${{GOOGLE_REDIRECT_URL}}
modules:
  - id: catalog
  - id: docs
  - id: test-one
  - id: test-two
  - id: test-three
  - id: test-four
  - id: test-five
  - id: test-six
